---
name: 'Platform.sh Database Backup and S3 Sync'
description: 'Execute a database backup/dump sync to S3.'
author: 'Mark Dorison'
inputs:
  platformsh_project:
    description: 'Platform.sh project ID.'
    required: true
  platformsh_environment:
    description: 'Platform.sh environment name.'
    required: true
  platformsh_relationship:
    description: 'Platform.sh relationship for multiple db projects.'
    required: false
  platformsh_app:
    description: 'Platform.sh app for multiple app projects.'
    required: false
  aws_s3_bucket:
    description: 'AWS S3 bucket name.'
    required: true
  db_dump_filename_base:
    description: 'Filename for the database dump. A timestamp will be appended after it.'
    required: false
    default: 'db-dump'
  aws_s3_directory:
    description: 'A directory within the S3 bucket with no proceeding / to copy the file to.'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'archive'
  color: 'gray-dark'
