---
name: Continuous-Integration
on:  # yamllint disable-line rule:truthy
  # Trigger the workflow on pushes to the main branch and all pull requests.
  push:
    branches:
      - main
  pull_request:
jobs:
  shellcheck:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Shellcheck
        run: |
          find . -name '*.sh' | xargs shellcheck -x

  yaml-lint:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4.2.2

      - name: YAML lint
        uses: ibiqlik/action-yamllint@master
        with:
          config_file: .yamllint.yml
